site_name:        QuickHull.jl
repo_url:         https://github.com/tlycken/QuickHull.jl
site_description: Finding convex hulls of 2D point sets in pure Julia
site_author:      tlycken

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home:
    - index.md
    - performance.md